### ISSUE TITLE
problem with terrible sys_errlist stuff in Watt-32

### ISSUE THREAD

**Issue by jmalak** [sezero/watt32#7]
I have a big issue with this stuff and Open Watcom tools.
The assumtion on which this stuff is based is wrong. 
It suppose that it depends on Compiler, but it depends on C run-time library version.
Each compiler Vendor delivery different CRTL with different version of compiler.
Watt-32 is compiled by one version but compiled library is used by any version of CRTL.
number of error messages can differ on run-time.
I thing that it should be changed to use Watt-32 errno and error codes independly from appropriate CRTL.
Simply can not copy sys_errlist into Watt-32 library and can not use sys_errlist for its own purpose.
It is big mismatch. By example OW CRTL time-to-time change number of messages. Watt-32 library created by different version of tools and linked with different version of CRTL has wrong number of messages and error codes are wrong.
Another problem is that Watt-32 tool for copy sys_errlist message create array which is incompatible with CRTL uses different modifiers then OW CRTL.

Do you plan to fix this issue?

**Comment by sezero** [comment]
I _think_ the whole errno/sys_errlist mess was due to keep
backwards compatibility with watt32's ancestors?? Not sure.
It is a gigantic and ugly and shameful mess, but it has been
there for a long time, and several software might depend on
that: no changing it -- and it's not mine to change either:
@gvanem is the main author of watt32, it should be reported
and discussed at https://github.com/gvanem/watt32/
